// app/about/page.tsx

import type { Metadata } from 'next';
import s from './page.module.scss';
import PageTitle from '@/components/atoms/common/PageTitle';
import Section_Banner from '@/components/pages/about/Section_Banner';
import TabNavigation from '@/components/atoms/buttons/TabNavigation';
import Section_01 from '@/components/pages/about/Section_01';
import Section_02 from '@/components/pages/about/Section_02';
import Section_03 from '@/components/pages/about/Section_03';
import Section_04 from '@/components/pages/about/Section_04';
import Section_05 from '@/components/pages/about/Section_05';
import FadeIn from '@/components/atoms/animation/FadeIn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const ABOUT_TABS = [
  { name: '소개', id: 'section-01' },
  { name: '학력', id: 'section-02' },
  { name: '자격 · 어학', id: 'section-03' },
  { name: '경력', id: 'section-04' },
  { name: '기술', id: 'section-05' },
];

export default async function About() {
  return (
    <main className={s['main']}>
      <FadeIn>
        <PageTitle>
          되는 방법을 먼저 찾고, <br className={s['mobile-br']} />더 나은 결과를
          만들어 가는 <br />
          4년차 프론트엔드 개발자 유강산 입니다.
        </PageTitle>
      </FadeIn>

      <FadeIn delay={0.3}>
        <Section_Banner />
      </FadeIn>

      <TabNavigation tabs={ABOUT_TABS} />

      <FadeIn threshold={0.2}>
        <div className={s['section-wrap']}>
          <Section_01 />

          <Section_02 />

          <Section_03 />

          <Section_04 />

          <Section_05 />
        </div>
      </FadeIn>
    </main>
  );
}
