// app/contact/page.tsx

import type { Metadata } from 'next';
import s from './page.module.scss';
import PageTitle from '@/components/atoms/common/PageTitle';
import Section_Banner from '@/components/pages/contact/Section_Banner';
import Section_Form from '@/components/pages/contact/Section_Form';
import FadeIn from '@/components/atoms/animation/FadeIn';
import Section_02 from '@/components/pages/main/Section_02';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Contact() {
  return (
    <main className={s['main']}>
      <FadeIn>
        <PageTitle>
          함께 작업하기를 희망 하시거나, <br />
          다른 문의가 있으신가요?
        </PageTitle>

        <Section_02 />
      </FadeIn>

      <Section_Form />
    </main>
  );
}
