import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/styles/globals.scss';

import InitialLoader from '@/components/session/InitialLoader';
import PageTransition from '@/components/session/PageTransition';

const themeScript = `
  (function() {
    try {
      var savedTheme = localStorage.getItem('theme');
      if (savedTheme) {
        document.documentElement.setAttribute('data-color-scheme', savedTheme);
      } else {
        document.documentElement.setAttribute('data-color-scheme', 'light');
      }
    } catch (e) {}
  })();
`;

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>

      <body>
        <InitialLoader />

        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
