// app/page.tsx

import type { Metadata } from 'next';
import s from './page.module.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Home() {
  return <main className={s['main']}>Hello, wolrd!</main>;
}
