// app/page.tsx

import type { Metadata } from 'next';
import s from './page.module.scss';
import ThemeToggle from '@/components/atoms/buttons/ThemeToggle';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Home() {
  return (
    <main className={s['main']}>
      <h1>Hello, wolrd!</h1>
      <ThemeToggle />
    </main>
  );
}
