// app/page.tsx

import type { Metadata } from 'next';
import s from './page.module.scss';
import ThemeToggle from '@/components/atoms/buttons/ThemeToggle';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Text() {
  return (
    <main className={s['main']}>
      <Link href={`/`}>메인</Link>
      <Link href={`/text`}>텍스트1</Link>
      <Link href={`/text2`}>텍스트2</Link>
      <h1>Hello, wolrd!</h1>
      <ThemeToggle />
    </main>
  );
}
