// app/works/page.tsx

import type { Metadata } from 'next';
import s from './page.module.scss';
import Section_01 from '@/components/pages/main/Section_01';
import PageTitle from '@/components/atoms/common/PageTitle';
import Section_Banner from '@/components/pages/works/Section_Banner';
import WorksContent from '@/components/pages/works/WorksContent';
import FadeIn from '@/components/atoms/animation/FadeIn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Works() {
  return (
    <main className={s['main']}>
      <FadeIn>
        <PageTitle>
          고객의 이야기를 가장 가까이에서 듣고,
          <br />
          만족을 넘어서는 경험을 제공해요.
        </PageTitle>
      </FadeIn>

      <Section_Banner />

      <FadeIn delay={0.5}>
        <WorksContent />
      </FadeIn>
    </main>
  );
}
